let name = "Smarak Das";
let school = "Saint Vincent School";
let grade = "🅐";
let section = "🅑";
let rollno = 23;
let marks1= 12;
let marks2 = 34;
let marks3 = 56;
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(rollno);
console.log(marks1);
console.log(marks2);
console.log(marks3);
